### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by piregg** [DiaLight/Ember#1]
This project looks really interesting! Do you happen to have a total idiot guide on how to get started please? I downloaded the latest release and tried running it from the game directory but I imagine there is a lot more to it than that? Do we have to use the release to compile our own patches or something? Or is there a way of having a prebuilt set ready to go? Thanks for your time.

**Comment by DiaLight** [comment]
Sorry for that. I will write a guide later in README. For now you need to unpack zip archive to anywhere you want and run launcher.exe. In the launcher window first you need to do is locate game directory. After that, the launcher will detect version of the game, and will tell you what version it detected. Currently the only game version supported is v1.70. Any other version will not be able to be patched correctly.
Then you can configure game resolution and start the game.
There seems to be the problem with missing ucrtbased.dll. I will figue it out later.

**Comment by DiaLight** [comment]
I described the process in [README](https://github.com/DiaLight/Ember/blob/fbbe36127f5bcbdd6757d05a56277a1e3b3e3d79/README.md). 
The missing ucrtbased.dll issue is gone in the latest version.
