### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by Trass3r** [DiaLight/Ember#3]
Doesn't build out of the box: https://github.com/Trass3r/Ember/actions/runs/3931612414

With submodules it fails to clone and without there's a CMake error regarding lodepng.

**Comment by DiaLight** [comment]
I adapted the project configuration to be installable and made the build requirement in the Dungeon Keeper 2 directory optional. I have no idea why github builder is using x64 compiler when I need x86.
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/Hostx[64](https://github.com/DiaLight/Ember/actions/runs/3933625684/jobs/6727528040#step:5:65)/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped

**Comment by Trass3r** [comment]
Yeah need to configure that.
https://github.com/Trass3r/Ember/blob/main/.github/workflows/CI.yml#L20

**Comment by Trass3r** [comment]
And then you could try
```yml
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: install/*
```

**Comment by DiaLight** [comment]
Thanks. Now github builds comlete release. One thing left unresolved. Only the latest build is complete and without errors. In Actions, there should be only the latest assembly with a green check mark, and the rest are erroneous. Do you know how to resolve this?

**Comment by Trass3r** [comment]
And you can remove the `-p` and the `dir ..`.

I was actually puzzled about that myself. Normally it works as expected and marks failed builds red.

**Comment by Trass3r** [comment]
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging
might reveal something.
Edit: ah yeah, if you re-run a workflow via the Actions UI you can actually tick a checkbox to enable that mode temporarily.

And the problem is the `dir ..` at the end as it determines the exit code of the whole step.
